// apps/v2_currisite/antigravity/prototype/src/components/QuizView.vue
<template>
  <div class="h-full flex flex-col items-center justify-center p-4 max-w-3xl mx-auto w-full">
    
    <!-- Progress Header -->
    <div class="w-full flex justify-between items-center mb-6 text-white px-2">
      <div class="flex items-center gap-2">
        <span class="text-2xl">🧪</span>
        <span class="font-bold">第 {{ currentIndex + 1 }} 題</span>
        <span class="text-white/60 text-sm">/ 共 {{ totalQuestions }} 題</span>
      </div>
      <div class="bg-white/20 backdrop-blur-sm px-3 py-1 rounded-full text-sm">
        得分: {{ score }}
      </div>
    </div>

    <!-- Question Card -->
    <div class="glass-card w-full rounded-3xl p-8 relative overflow-hidden min-h-[400px] flex flex-col">
      <!-- Background Decor -->
      <div class="absolute -top-10 -right-10 w-40 h-40 bg-indigo-500/10 rounded-full blur-3xl"></div>
      <div class="absolute -bottom-10 -left-10 w-40 h-40 bg-purple-500/10 rounded-full blur-3xl"></div>

      <!-- Question Text -->
      <div class="mb-8 relative z-10 flex-grow">
        <span class="inline-block bg-indigo-100 text-indigo-700 text-xs px-2 py-1 rounded-md mb-3 font-bold tracking-wider">
          {{ currentQuestion.category }}
        </span>
        <h2 class="text-2xl font-bold text-gray-800 leading-relaxed">
          {{ currentQuestion.question }}
        </h2>
      </div>

      <!-- Options Grid -->
      <div class="grid gap-4 relative z-10">
        <button 
          v-for="(option, index) in currentQuestion.options" 
          :key="index"
          @click="handleAnswer(index)"
          :disabled="showFeedback"
          class="w-full p-4 rounded-xl text-left transition-all duration-200 border-2 flex items-center group relative overflow-hidden"
          :class="getOptionClass(index)"
        >
          <!-- Hover Gradient -->
          <div class="absolute inset-0 bg-white/50 opacity-0 group-hover:opacity-100 transition-opacity" v-if="!showFeedback"></div>
          
          <!-- Option Label (A, B, C...) -->
          <div 
            class="w-8 h-8 rounded-full flex items-center justify-center mr-4 text-sm font-bold shrink-0 transition-colors"
            :class="getOptionLabelClass(index)"
          >
            {{ ['A', 'B', 'C', 'D'][index] }}
          </div>
          
          <span class="font-medium text-lg relative z-10" :class="getOptionTextClass(index)">
            {{ option }}
          </span>

          <!-- Feedback Icon -->
          <div class="ml-auto text-2xl" v-if="showFeedback && index === currentQuestion.correctAnswer">
            ✅
          </div>
          <div class="ml-auto text-2xl" v-if="showFeedback && selectedAnswer === index && index !== currentQuestion.correctAnswer">
            ❌
          </div>
        </button>
      </div>

      <!-- Explanation / Next Button -->
      <div v-if="showFeedback" class="mt-6 pt-6 border-t border-gray-200/50 animate-fade-in">
        <div class="bg-blue-50/80 rounded-xl p-4 mb-4 text-blue-900">
          <p class="font-bold text-sm mb-1">💡 小知識</p>
          <p>{{ currentQuestion.explanation }}</p>
        </div>
        
        <button 
          @click="nextQuestion"
          class="w-full py-4 bg-gradient-to-r from-indigo-600 to-purple-600 text-white rounded-xl font-bold text-lg shadow-lg hover:shadow-xl hover:scale-[1.02] transition-all active:scale-95"
        >
          {{ isLastQuestion ? '查看結果 🏆' : '下一題 ➡️' }}
        </button>
      </div>

    </div>
  </div>
</template>

<script setup>
import { computed, ref } from 'vue'

const props = defineProps({
  questions: {
    type: Array,
    required: true
  }
})

const emit = defineEmits(['finish-quiz'])

const currentIndex = ref(0)
const score = ref(0)
const selectedAnswer = ref(null)
const showFeedback = ref(false)
const history = ref([]) // Track answers for review

const currentQuestion = computed(() => props.questions[currentIndex.value] || {})
const totalQuestions = computed(() => props.questions.length)
const isLastQuestion = computed(() => currentIndex.value === props.questions.length - 1)

// Colors logic
const getOptionClass = (index) => {
  if (!showFeedback.value) {
    return 'bg-white/40 border-white/20 hover:border-indigo-300 hover:bg-white/60'
  }
  
  if (index === currentQuestion.value.correctAnswer) {
    return 'bg-green-100/80 border-green-500 text-green-900'
  }
  
  if (index === selectedAnswer.value) {
    return 'bg-red-100/80 border-red-500 text-red-900'
  }
  
  return 'bg-white/20 border-transparent opacity-50'
}

const getOptionLabelClass = (index) => {
  if (!showFeedback.value) return 'bg-white text-indigo-600 group-hover:bg-indigo-600 group-hover:text-white'
  if (index === currentQuestion.value.correctAnswer) return 'bg-green-500 text-white'
  if (index === selectedAnswer.value) return 'bg-red-500 text-white'
  return 'bg-gray-200 text-gray-500'
}

const getOptionTextClass = (index) => {
  if (!showFeedback.value) return 'text-gray-700'
  return ''
}

const handleAnswer = (index) => {
  if (showFeedback.value) return
  
  selectedAnswer.value = index
  showFeedback.value = true
  
  const isCorrect = index === currentQuestion.value.correctAnswer
  if (isCorrect) {
    score.value += 1
  }

  // Record history
  history.value.push({
    questionId: currentQuestion.value.id,
    selected: index,
    correct: currentQuestion.value.correctAnswer,
    isCorrect
  })
}

const nextQuestion = () => {
  if (isLastQuestion.value) {
    emit('finish-quiz', {
      score: score.value,
      total: totalQuestions.value,
      history: history.value
    })
  } else {
    currentIndex.value++
    selectedAnswer.value = null
    showFeedback.value = false
  }
}
</script>

<style scoped>
.animate-fade-in {
  animation: fadeIn 0.4s ease-out;
}

@keyframes fadeIn {
  from { opacity: 0; transform: translateY(10px); }
  to { opacity: 1; transform: translateY(0); }
}
</style>

// apps/v3_eidos_lovable/src/components/QuizView.tsx
import { useState, useCallback } from 'react';
import { Question, SUBJECT_THEME_MAP, Subject } from '@/data/config';

interface QuizViewProps {
  questions: Question[];
  quizType: string;
  subject: Subject;
  onFinish: (score: number, total: number, wrongQuestions: Question[], answeredList: { question: Question; isCorrect: boolean; selected: number }[]) => void;
  onBack: () => void;
  onSaveAnswer: (questionId: string, isCorrect: boolean) => void;
  initialIndex?: number;
  initialScore?: number;
  initialAnswered?: { question: Question; isCorrect: boolean; selected: number }[];
}

export default function QuizView({
  questions, quizType, subject, onFinish, onBack, onSaveAnswer,
  initialIndex = 0, initialScore = 0, initialAnswered = [],
}: QuizViewProps) {
  const [currentIndex, setCurrentIndex] = useState(initialIndex);
  const [score, setScore] = useState(initialScore);
  const [selectedOption, setSelectedOption] = useState<number | null>(null);
  const [confirmed, setConfirmed] = useState(false);
  const [answered, setAnswered] = useState(initialAnswered);
  const [sessionCorrect, setSessionCorrect] = useState(initialAnswered.filter(a => a.isCorrect).length);
  const [sessionWrong, setSessionWrong] = useState(initialAnswered.filter(a => !a.isCorrect).length);

  const theme = SUBJECT_THEME_MAP[subject];
  const current = questions[currentIndex];
  const isLast = currentIndex === questions.length - 1;
  const progress = ((currentIndex + (confirmed ? 1 : 0)) / questions.length) * 100;

  const handleConfirm = useCallback(() => {
    if (selectedOption === null || confirmed) return;
    const isCorrect = selectedOption === current.normalizedAnswer;
    setConfirmed(true);
    if (isCorrect) {
      setScore(s => s + 1);
      setSessionCorrect(c => c + 1);
    } else {
      setSessionWrong(w => w + 1);
    }
    const entry = { question: current, isCorrect, selected: selectedOption };
    setAnswered(prev => [...prev, entry]);
    onSaveAnswer(current.id, isCorrect);
  }, [selectedOption, confirmed, current, onSaveAnswer]);

  const handleNext = useCallback(() => {
    if (isLast) {
      const wrongQs = answered.filter(a => !a.isCorrect).map(a => a.question);
      // Include current if just confirmed and wrong
      if (confirmed && selectedOption !== current.normalizedAnswer) {
        wrongQs.push(current);
      }
      onFinish(score + (confirmed && selectedOption === current.normalizedAnswer ? 0 : 0), questions.length, wrongQs, answered);
      return;
    }
    setCurrentIndex(i => i + 1);
    setSelectedOption(null);
    setConfirmed(false);
  }, [isLast, confirmed, selectedOption, current, score, questions.length, answered, onFinish]);

  const handleFinish = () => {
    const wrongQs = answered.filter(a => !a.isCorrect).map(a => a.question);
    onFinish(score, questions.length, wrongQs, answered);
  };

  if (!current) return null;

  const optionLabels = ['A', 'B', 'C', 'D'];

  return (
    <div className="max-w-lg mx-auto px-4 py-4 space-y-4">
      {/* Top bar */}
      <div className="flex items-center gap-3">
        <button onClick={onBack} className="text-muted-foreground hover:text-foreground transition-colors text-lg">
          ← 返回
        </button>
        <span className="text-sm text-muted-foreground ml-auto">{quizType}</span>
      </div>

      {/* Progress */}
      <div className="space-y-1">
        <div className="h-3 bg-muted rounded-full overflow-hidden">
          <div
            className={`h-full gradient-${theme} rounded-full transition-all duration-500`}
            style={{ width: `${progress}%` }}
          />
        </div>
        <div className="flex justify-between text-xs text-muted-foreground">
          <span>第 {currentIndex + 1} 題 / 共 {questions.length} 題</span>
          <span>✓ {sessionCorrect}　✗ {sessionWrong}</span>
        </div>
      </div>

      {/* Question card */}
      <div className="bg-card rounded-2xl border shadow-sm p-5 space-y-4">
        <div className="flex gap-2 flex-wrap">
          <span className={`text-xs px-2 py-0.5 rounded-full subject-bg-${theme}-light subject-text-${theme} font-medium`}>
            {current.category}
          </span>
          <span className="text-xs px-2 py-0.5 rounded-full bg-muted text-muted-foreground">
            選擇題
          </span>
        </div>

        <p className="text-lg font-medium leading-relaxed">{current.question}</p>

        <div className="space-y-2">
          {current.options.map((opt, i) => {
            let optClass = 'bg-background border hover:border-primary/50';
            if (confirmed) {
              if (i === current.normalizedAnswer) {
                optClass = 'bg-correct-light border-2 border-correct';
              } else if (i === selectedOption && i !== current.normalizedAnswer) {
                optClass = 'bg-wrong-light border-2 border-wrong';
              } else {
                optClass = 'bg-muted/50 border opacity-60';
              }
            } else if (i === selectedOption) {
              optClass = `subject-bg-${theme}-light border-2 subject-border-${theme}`;
            }
            return (
              <button
                key={i}
                onClick={() => !confirmed && setSelectedOption(i)}
                disabled={confirmed}
                className={`w-full text-left px-4 py-3 rounded-xl transition-all flex items-start gap-3 ${optClass}`}
              >
                <span className="font-bold text-muted-foreground shrink-0">{optionLabels[i]}</span>
                <span>{opt}</span>
              </button>
            );
          })}
        </div>

        {/* Explanation */}
        {confirmed && current.explanation && (
          <div className={`p-3 rounded-xl text-sm ${
            selectedOption === current.normalizedAnswer ? 'bg-correct-light' : 'bg-wrong-light'
          }`}>
            <p className="font-bold mb-1">
              {selectedOption === current.normalizedAnswer ? '✅ 答對了！' : '❌ 答錯了！'}
            </p>
            <p className="text-muted-foreground">{current.explanation}</p>
          </div>
        )}
      </div>

      {/* Action buttons */}
      <div className="flex gap-3">
        {!confirmed ? (
          <button
            onClick={handleConfirm}
            disabled={selectedOption === null}
            className={`flex-1 py-3 rounded-xl font-bold text-lg transition-all ${
              selectedOption !== null
                ? `gradient-${theme} text-primary-foreground shadow-md active:scale-95`
                : 'bg-muted text-muted-foreground cursor-not-allowed'
            }`}
          >
            確認答案
          </button>
        ) : isLast ? (
          <button
            onClick={handleFinish}
            className={`flex-1 py-3 rounded-xl font-bold text-lg gradient-${theme} text-primary-foreground shadow-md active:scale-95 transition-all`}
          >
            🎉 查看結果
          </button>
        ) : (
          <button
            onClick={handleNext}
            className={`flex-1 py-3 rounded-xl font-bold text-lg gradient-${theme} text-primary-foreground shadow-md active:scale-95 transition-all`}
          >
            下一題 →
          </button>
        )}
      </div>
    </div>
  );
}
