// src/components/StatisticsView.vue
<template>
  <div class="statistics-view">
    <div class="statistics-container">
      <div class="statistics-header">
        <button @click="back" class="back-btn">← 返回</button>
        <h1>📊 答題統計</h1>
      </div>

      <div class="statistics-content">
        <!-- 總體統計 -->
        <div v-if="statistics" class="statistics-section">
          <h2>📊 總體統計</h2>
          <div class="stats-grid">
            <div class="stat-card">
              <div class="stat-label">總答題數</div>
              <div class="stat-value">{{ statistics.totalQuestions }}</div>
            </div>
            <div class="stat-card">
              <div class="stat-label">總正確數</div>
              <div class="stat-value correct">{{ statistics.totalCorrect }}</div>
            </div>
            <div class="stat-card">
              <div class="stat-label">總錯誤數</div>
              <div class="stat-value wrong">{{ statistics.totalWrong }}</div>
            </div>
            <div class="stat-card">
              <div class="stat-label">正確率</div>
              <div class="stat-value">{{ statistics.accuracy }}%</div>
            </div>
          </div>
        </div>

        <!-- 練習歷史 -->
        <div v-if="filteredHistory.length > 0" class="practice-history-section">
          <h2>📝 練習歷史記錄 {{ subject ? `(${getSubjectDisplay(subject)})` : '(全部科目)' }}</h2>
          <div class="history-list">
            <div 
              v-for="(record, index) in filteredHistory" 
              :key="record.id || index"
              class="history-item"
            >
              <div class="history-header">
                <div class="history-type-wrapper">
                  <span class="history-subject">{{ getSubjectDisplay(record.subject) }}</span>
                  <span class="history-type">{{ record.type }}</span>
                </div>
                <span class="history-date">{{ new Date(record.timestamp).toLocaleString('zh-TW') }}</span>
              </div>
              <div class="history-stats">
                <span>正確率: {{ parseFloat(record.accuracy || 0).toFixed(1) }}%</span>
                <span>得分: {{ record.score }}/{{ record.count }}</span>
                <span>時間: {{ formatDuration(record.duration || 0) }}</span>
              </div>
            </div>
          </div>
        </div>
        <div v-else class="empty-message">
          <p>還沒有練習記錄，快去開始練習吧！</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, watch, computed } from 'vue'
import { getStatistics, getPracticeHistory } from '../utils/storage.js'
import { SUBJECT_NAMES, SUBJECT_ICONS } from '../data/questions.js'

const props = defineProps({
  subject: {
    type: String,
    default: null
  }
})

const emit = defineEmits(['back'])

const statistics = ref(null)
const practiceHistory = ref([])

// 获取科目显示名称
const getSubjectDisplay = (subjectKey) => {
  if (!subjectKey) return ''
  const name = SUBJECT_NAMES[subjectKey] || subjectKey
  const icon = SUBJECT_ICONS[subjectKey] || '📚'
  return `${icon} ${name}`
}

// 过滤历史记录（如果指定了科目，只显示该科目的记录）
const filteredHistory = computed(() => {
  if (!props.subject) {
    return practiceHistory.value
  }
  return practiceHistory.value.filter(record => record.subject === props.subject)
})

onMounted(() => {
  statistics.value = getStatistics(props.subject)
  practiceHistory.value = getPracticeHistory().slice().reverse() // 最新的在前面
})

watch(() => props.subject, () => {
  statistics.value = getStatistics(props.subject)
})

const formatDuration = (seconds) => {
  if (seconds < 60) {
    return `${seconds}秒`
  }
  const minutes = Math.floor(seconds / 60)
  const secs = seconds % 60
  return `${minutes}分${secs}秒`
}

const back = () => {
  emit('back')
}
</script>

<style scoped>
.statistics-view {
  min-height: 100vh;
  padding: 20px;
  padding-top: 70px;
  background: #f5f5f5;
}

.statistics-container {
  max-width: 900px;
  margin: 0 auto;
  background: white;
  border-radius: 20px;
  padding: 30px;
  box-shadow: 0 10px 40px rgba(0, 0, 0, 0.2);
}

.statistics-header {
  margin-bottom: 30px;
  text-align: center;
  position: relative;
}

.back-btn {
  position: absolute;
  left: 0;
  background: #f0f0f0;
  border: none;
  padding: 8px 15px;
  border-radius: 8px;
  cursor: pointer;
  font-size: 0.9em;
  transition: background 0.3s;
}

.back-btn:hover {
  background: #e0e0e0;
}

.statistics-header h1 {
  font-size: 2.5em;
  color: #667eea;
  margin: 20px 0;
}

.statistics-content {
  display: flex;
  flex-direction: column;
  gap: 30px;
}

.statistics-section h2,
.practice-history-section h2 {
  font-size: 1.8em;
  color: #667eea;
  margin-bottom: 20px;
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 20px;
  margin-bottom: 20px;
}

.stat-card {
  background: #f9f9f9;
  padding: 20px;
  border-radius: 12px;
  text-align: center;
  border: 2px solid #e0e0e0;
  transition: all 0.3s;
}

.stat-card:hover {
  border-color: #667eea;
  transform: translateY(-2px);
  box-shadow: 0 5px 15px rgba(102, 126, 234, 0.2);
}

.stat-label {
  font-size: 1em;
  color: #666;
  margin-bottom: 10px;
}

.stat-value {
  font-size: 2.5em;
  font-weight: bold;
  color: #667eea;
}

.stat-value.correct {
  color: #4caf50;
}

.stat-value.wrong {
  color: #f44336;
}

.practice-history-section {
  margin-top: 30px;
}

.history-list {
  display: flex;
  flex-direction: column;
  gap: 15px;
  max-height: 600px;
  overflow-y: auto;
}

.history-item {
  background: #f9f9f9;
  padding: 15px;
  border-radius: 10px;
  border-left: 4px solid #667eea;
  transition: all 0.3s;
}

.history-item:hover {
  background: #f0f0f0;
  transform: translateX(5px);
}

.history-header {
  display: flex;
  justify-content: space-between;
  margin-bottom: 10px;
  align-items: center;
}

.history-type-wrapper {
  display: flex;
  flex-direction: column;
  gap: 5px;
}

.history-subject {
  font-weight: bold;
  color: #4caf50;
  font-size: 1em;
}

.history-type {
  font-weight: bold;
  color: #667eea;
  font-size: 1.1em;
}

.history-date {
  font-size: 0.9em;
  color: #999;
}

.history-stats {
  display: flex;
  gap: 20px;
  font-size: 0.95em;
  color: #666;
  flex-wrap: wrap;
}

.empty-message {
  text-align: center;
  padding: 40px;
  color: #999;
  font-size: 1.2em;
}
</style>

// apps/v3_eidos_lovable/src/components/StatisticsView.tsx
import { Grade, Semester, Publisher, Subject, SUBJECT_THEME_MAP, SEMESTER_NAMES, Question } from '@/data/config';
import { getStatistics, getPracticeHistory, getAnswerHistory } from '@/utils/storage';

interface StatisticsViewProps {
  grade: Grade;
  semester: Semester;
  publisher: Publisher;
  subject: Subject;
  questions: Question[];
  categories: string[];
  onBack: () => void;
}

export default function StatisticsView({
  grade, semester, publisher, subject, questions, categories, onBack,
}: StatisticsViewProps) {
  const theme = SUBJECT_THEME_MAP[subject];
  const stats = getStatistics(grade, subject, semester, publisher);
  const history = getPracticeHistory(grade, subject, semester, publisher);
  const answerHistory = getAnswerHistory(grade, subject, semester, publisher);

  // Category stats
  const catStats = categories.map(cat => {
    const catQs = questions.filter(q => q.category === cat);
    let total = 0, correct = 0;
    catQs.forEach(q => {
      const record = answerHistory[q.id];
      if (record) {
        total += record.total;
        correct += record.correct;
      }
    });
    return { category: cat, total, correct, wrong: total - correct, accuracy: total > 0 ? Math.round((correct / total) * 100) : 0 };
  });

  // Practice history stats
  const practiceHistory = history.filter(h => h.type?.includes('挑戰')); 
  const avgScore = practiceHistory.length > 0
    ? Math.round(practiceHistory.reduce((s, h) => s + h.accuracy, 0) / practiceHistory.length)
    : 0;

  return (
    <div className="max-w-lg mx-auto px-4 py-4 space-y-6">
      <div className="flex items-center gap-3">
        <button onClick={onBack} className="text-muted-foreground hover:text-foreground transition-colors text-lg">← 返回</button>
        <div>
          <h1 className="text-xl font-bold">📊 學習統計報告</h1>
          <p className="text-xs text-muted-foreground">{grade}年級 {subject} {SEMESTER_NAMES[semester]} ({publisher}版)</p>
          <p className="text-[10px] text-muted-foreground mt-0.5">對照選單選擇的科目與年級分別統計，含做題日期、答對率等</p>
        </div>
      </div>

      {/* Overall */}
      <div className={`rounded-2xl p-5 subject-bg-${theme}-light space-y-3`}>
        <h2 className="font-bold">綜合練習統計</h2>
        {practiceHistory.length > 0 ? (
          <div className="grid grid-cols-2 gap-2">
            <StatBox label="練習次數" value={practiceHistory.length} />
            <StatBox label="平均正確率" value={`${avgScore}%`} />
            <StatBox label="總答題" value={stats.totalAnswered} />
            <StatBox label="總正確" value={stats.totalCorrect} />
          </div>
        ) : (
          <p className="text-sm text-muted-foreground text-center py-3">此項目尚無練習記錄</p>
        )}
      </div>

      {/* Category stats */}
      <div className="bg-card rounded-2xl border p-5 space-y-3">
        <h2 className="font-bold">分類複習統計</h2>
        {catStats.some(c => c.total > 0) ? (
          <div className="space-y-2">
            {catStats.map(c => (
              <div key={c.category} className="space-y-1">
                <div className="flex justify-between text-sm">
                  <span>{c.category}</span>
                  <span className="text-muted-foreground">{c.accuracy}% ({c.correct}/{c.total})</span>
                </div>
                <div className="h-2 bg-muted rounded-full overflow-hidden">
                  <div className={`h-full gradient-${theme} rounded-full transition-all`} style={{ width: `${c.accuracy}%` }} />
                </div>
              </div>
            ))}
          </div>
        ) : (
          <p className="text-sm text-muted-foreground text-center py-3">此項目尚無分類練習記錄</p>
        )}
      </div>

      {/* Practice history */}
      <div className="bg-card rounded-2xl border p-5 space-y-3">
        <h2 className="font-bold">練習歷史記錄</h2>
        {history.length > 0 ? (
          <div className="space-y-2 text-sm">
            {history.slice(0, 10).map(h => (
              <div key={h.id} className="flex justify-between items-center py-2 border-b last:border-0">
                <div>
                  <div className="font-medium">{h.type}</div>
                  <div className="text-xs text-muted-foreground">{new Date(h.timestamp).toLocaleString('zh-TW')}</div>
                </div>
                <div className="text-right">
                  <div className="font-bold">{h.accuracy}%</div>
                  <div className="text-xs text-muted-foreground">{h.score}/{h.count}</div>
                </div>
              </div>
            ))}
          </div>
        ) : (
          <p className="text-sm text-muted-foreground text-center py-3">此項目尚無練習記錄</p>
        )}
      </div>
    </div>
  );
}

function StatBox({ label, value }: { label: string; value: string | number }) {
  return (
    <div className="bg-card rounded-xl p-3 text-center">
      <div className="text-xl font-bold">{value}</div>
      <div className="text-xs text-muted-foreground">{label}</div>
    </div>
  );
}
